backend/libs/piston/examples/blogserver/api/urls.py
from django.conf.urls.defaults import *
from piston.resource import Resource
from piston.authentication import HttpBasicAuthentication
from piston.doc import documentation_view

from blogserver.api.handlers import BlogpostHandler

auth = HttpBasicAuthentication(realm='My sample API')

blogposts = Resource(handler=BlogpostHandler, authentication=auth)

urlpatterns = patterns('',
    url(r'^posts/$', blogposts),
    url(r'^posts/(?P<emitter_format>.+)/$', blogposts),
    url(r'^posts\.(?P<emitter_format>.+)', blogposts, name='blogposts'),

    # automated documentation
    url(r'^$', documentation_view),
)

backend/libs/piston/examples/blogserver/blog/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('blogserver.blog.views',
    url(r'^$', 'posts', name='posts'),
    url(r'^js$', 'test_js'),
)

backend/libs/piston/examples/blogserver/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('blogserver.blog.urls')),
    (r'^api/', include('blogserver.api.urls')),
    (r'^admin/(.*)', admin.site.root),
)

backend/libs/piston/examples/blogserver/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

class Blogpost(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, related_name='posts')
    created_on = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.title

admin.site.register(Blogpost)

backend/libs/piston/examples/blogserver/blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from blogserver.blog.models import Blogpost

def posts(request):
    posts = Blogpost.objects.all()

    return render_to_response("posts.html", {
        'posts': posts },
        RequestContext(request))
    
def test_js(request):
    return render_to_response('test_js.html', {}, RequestContext(request))

backend/libs/piston/examples/blogserver/templates/posts.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<title>Blogposts</title>

</head>

<body>

	<h1>Posts</h1>
	
	{% for post in posts %}
	
		<h3>{{ post.title }}</h3>
	
		<div>
			
			{{ post.content}}
			
		</div>
		
		<div>
			Written on {{ post.created_on }} by {{ post.author.username }}.
		</div>
	
	{% endfor %}

</body>

</html>

backend/libs/piston/examples/blogserver/templates/test_js.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>

<title>Test</title>

<script type="text/javascript">
// Basic 64 of user password
var auth = "Basic dGVzdHVzZXI6Zm9vYmFy";

function success_callback() {
	$("<h3>").text(this.title).appendTo("#content");
	$("<div>").text(this.content).appendTo("#content");
	$("<h4>").text(this.created_on).appendTo("#content");
};

$(function() {
	var dict = {
		url: "/api/posts.json",
		beforeSend: function(request) {
			request.setRequestHeader('Authorization', auth)
		},
		success: function(json, textStatus) {$.each(json, success_callback)},
		dataType: "json"
	};
		
	$.ajax(dict);
});

function send_form() {
	send_dict = {
		url: "/api/posts.json",
		beforeSend: function(request) {
				request.setRequestHeader('Authorization', auth)
		},
		type: "POST",
		data: $("#id_form").serialize(),
		processData: false,
		dataType: "json",
		success: function(json, textStatus) {
			$("<h3>").text(json.title).appendTo("#content");
			$("<div>").text(json.content).appendTo("#content");
			$("<h4>").text(json.created_on).appendTo("#content");
		}
	};
	
	$.ajax(send_dict);

	return false;
};
</script>
</head>

<body>
	<h1>JS Test</h1>
	<div id="content">
	</div>
	<form id="id_form" action="." method="post">
		<label for="id_title">Title:</label>
		<input type="text" id="id_title" name="title" />
		<br />
		<label for="id_content">Content:</label>
		<textarea cols="40" rows="20" id="id_content" name="content"></textarea>
		<br />
		<input type="submit" onclick="return send_form();" value="Submit" />
	</form>
</body>

</html>